# Generated by Django 5.2.3 on 2025-07-09 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watch_later_by',
            field=models.ManyToManyField(blank=True, related_name='watch_later', to=settings.AUTH_USER_MODEL),
        ),
    ]
